[pytest]

markers =
    smoke: Critical path tests (must pass)
    regression: Full test suite
    ui: UI-related tests
    api: API tests
    e2e: End-to-end tests
    
    banking: BankingProject tests
    saucedemo: Saucedemo tests
    restfulbooker: RestfulBooker tests

addopts = 
    -v
    --tb=short
    --strict-markers
    --maxfail=5
    -p no:cacheprovider
    --capture=no
    --dist=loadgroup
    --alluredir=allure-results

testpaths = tests

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S